version: '3.9'

services:
    neo4j:
        container_name: neo4j
        restart: on-failure
        build: ./neo4j
        # user: "1001:1001"
        volumes:
          # - /neo4j/data:/data 
          # - /neo4j/logs:/logs 
          # - /neo4j/import:/var/lib/neo4j/import 
          # - /neo4j/plugins:/plugins
          # - db-backups:/dumps
          - neo4j-dumps:/dumps
          - neo4j-data:/data
        ports:
          - "7474:7474"
          - "7687:7687"
        env_file:
          - .env
        networks:
          - db_comm

    update:
        container_name: update
        restart: always
        build:
          context: ./ 
          dockerfile: ./update/Dockerfile
        env_file:
          - .env
        networks:
          - db_comm

networks:
  db_comm:
    driver: bridge
    ipam:
      driver: default

volumes:
    neo4j-dumps:
      driver: local
      driver_opts:
        type: nfs
        o: nfsvers=4,addr=${nfsIP},nolock,soft,rw
        device: $nfsPath
    neo4j-data: